#!/bin/bash

# Script to create Ubuntu 22.04 LTS template for Chef 360 deployment
set -e

echo "=== Creating Ubuntu 22.04 LTS Template for Proxmox ==="
echo ""

# Configuration
VMID="9000"
VMNAME="ubuntu-22.04-template"
STORAGE="local-lvm"
ISO_STORAGE="local"
ISO_URL="https://releases.ubuntu.com/22.04/ubuntu-22.04.4-live-server-amd64.iso"
ISO_NAME="ubuntu-22.04.4-live-server-amd64.iso"

echo "1. Downloading Ubuntu 22.04 LTS ISO (if not already present)..."
echo "   You can skip this if you already have the ISO on your Proxmox host"
echo ""
echo "   Run this on your Proxmox host:"
echo "   cd /var/lib/vz/template/iso"
echo "   wget -O $ISO_NAME $ISO_URL"
echo ""

echo "2. Create VM template with these commands on your Proxmox host:"
echo ""
echo "# Create the VM"
echo "qm create $VMID --name $VMNAME --memory 2048 --cores 2 --net0 virtio,bridge=vmbr0"
echo ""
echo "# Add the Ubuntu ISO"
echo "qm set $VMID --ide2 $ISO_STORAGE:iso/$ISO_NAME,media=cdrom"
echo ""
echo "# Add a disk"
echo "qm set $VMID --scsi0 $STORAGE:32,format=qcow2"
echo ""
echo "# Set the SCSI controller"
echo "qm set $VMID --scsihw virtio-scsi-pci"
echo ""
echo "# Set boot order"
echo "qm set $VMID --boot order=scsi0"
echo ""
echo "# Enable QEMU agent"
echo "qm set $VMID --agent enabled=1"
echo ""
echo "# Start the VM for installation"
echo "qm start $VMID"
echo ""

echo "3. Install Ubuntu 22.04:"
echo "   - Access VM console in Proxmox web interface"
echo "   - Follow Ubuntu installation wizard"
echo "   - Create a user 'ubuntu' with password"
echo "   - Install OpenSSH server"
echo "   - Install qemu-guest-agent during installation or after:"
echo "     sudo apt update && sudo apt install -y qemu-guest-agent"
echo "   - Enable cloud-init support:"
echo "     sudo apt install -y cloud-init"
echo ""

echo "4. Prepare template (run these in the VM):"
echo "   sudo apt update && sudo apt upgrade -y"
echo "   sudo apt install -y qemu-guest-agent cloud-init"
echo "   sudo systemctl enable qemu-guest-agent"
echo "   sudo cloud-init clean"
echo "   sudo rm -rf /var/lib/cloud/instances"
echo "   sudo rm /etc/machine-id"
echo "   sudo touch /etc/machine-id"
echo "   sudo poweroff"
echo ""

echo "5. Convert to template (run on Proxmox host):"
echo "   qm template $VMID"
echo ""

echo "6. Alternative: Quick template creation using cloud image:"
echo ""
echo "# Download Ubuntu cloud image"
echo "cd /var/lib/vz/template/iso"
echo "wget https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img"
echo ""
echo "# Create VM"
echo "qm create $VMID --name $VMNAME --memory 2048 --cores 2 --net0 virtio,bridge=vmbr0"
echo ""
echo "# Import the cloud image"
echo "qm disk import $VMID ubuntu-22.04-server-cloudimg-amd64.img $STORAGE"
echo ""
echo "# Attach the disk"
echo "qm set $VMID --scsi0 $STORAGE:vm-$VMID-disk-0"
echo ""
echo "# Set other options"
echo "qm set $VMID --scsihw virtio-scsi-pci --boot order=scsi0"
echo "qm set $VMID --agent enabled=1"
echo "qm set $VMID --ide2 $STORAGE:cloudinit"
echo "qm set $VMID --serial0 socket --vga serial0"
echo ""
echo "# Convert to template"
echo "qm template $VMID"
echo ""

echo "Once the template is created, you can deploy Chef 360 infrastructure!"
