#cloud-config
hostname: ${hostname}
fqdn: ${hostname}

# System configuration for default user
system_info:
  default_user:
    name: ubuntu
    plain_text_passwd: ubuntu123!
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

# User configuration - IMPROVED
users:
  - name: ubuntu
    plain_text_passwd: ubuntu123!
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    home: /home/ubuntu
    ssh_authorized_keys:
      - ${ssh_public_key}

# Enable password authentication
ssh_pwauth: true

# Set password using multiple methods for reliability
chpasswd:
  expire: false
  users:
    - name: ubuntu
      password: ubuntu123!
      type: text

# Network configuration for static IP
write_files:
  - path: /etc/netplan/01-netcfg.yaml
    content: |
      network:
        version: 2
        ethernets:
          ens18:
            dhcp4: false
            addresses:
              - ${ip_address}/23
            routes:
              - to: default
                via: ${gateway}
            nameservers:
              addresses:
                - 8.8.8.8
                - 8.8.4.4
    permissions: '0644'

# Update packages
package_update: true
package_upgrade: true

# Install required packages
packages:
  - curl
  - wget
  - unzip
  - jq
  - openssh-server

# Run commands at boot - IMPROVED with better user setup
runcmd:
  # Network setup
  - netplan apply
  - systemctl restart systemd-networkd
  # User setup - multiple attempts for reliability
  - echo 'ubuntu:ubuntu123!' | chpasswd
  - passwd -u ubuntu
  - usermod -aG sudo ubuntu
  - usermod -s /bin/bash ubuntu
  - mkdir -p /home/ubuntu/.ssh
  - chown ubuntu:ubuntu /home/ubuntu/.ssh
  - chmod 700 /home/ubuntu/.ssh
  # SSH setup
  - systemctl enable ssh
  - systemctl start ssh
  - systemctl restart ssh
  # Enable console login
  - systemctl enable getty@tty1.service
  - systemctl start getty@tty1.service
  # Workstation setup script
  - printf '%s' "${user_data_script}" | base64 -d > /tmp/workstation-install.sh
  - chmod +x /tmp/workstation-install.sh
  - nohup /tmp/workstation-install.sh > /var/log/workstation-install.log 2>&1 &
  # Debug logging
  - echo "Workstation setup completed at $(date)" >> /var/log/setup-debug.log
  - id ubuntu >> /var/log/setup-debug.log
  - grep ubuntu /etc/passwd >> /var/log/setup-debug.log
  - systemctl status ssh >> /var/log/setup-debug.log

# SSH configuration
ssh_deletekeys: false
ssh_genkeytypes: ['rsa', 'ecdsa', 'ed25519']

# Console access
disable_root: false
ssh_authorize_keys: true

# Final message
final_message: "Workstation cloud-init completed. Login: ubuntu/ubuntu123!"